"use strict";
(self.webpackJsonp = self.webpackJsonp || []).push([
  [144],
  {
    461: function (e, t, o) {
      o.r(t),
        (t.default = {
          build:
            "a1fabafcc4b524ea3dc5b7b35f015e7da7896d2a80b1794f2dcaa8c2401665ca",
          constants: [
            "About can't be empty.",
            "About is too long.",
            "About",
            "You can't join this group because it has ended.",
            "You can't join this group because it is full.",
            "Couldn't join group. Please try again.",
            "You can't join this group because your invite is no longer valid.",
            "Account",
            "Save name",
            "Couldn't add participant. Please try again.",
            "You can't add participants because this group has ended.",
            "You can't add participants because you're not an admin.",
            "You can't add participants because you're not a participant.",
            "Couldn't add participant. Check your Internet connection and try again.",
            "You've added too many contacts to groups too quickly. Try again later.",
            "Invite",
            "Send invite",
            "Adding…",
            "Add participants",
            "Add to contacts",
            "All media",
            "Already in group",
            "Critical error",
            "Archived",
            "Archived chats",
            "Audio",
            "Contacts",
            "GIF",
            "Location",
            "Photo",
            "Video",
            "Audio",
            "This account is not allowed to use W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp",
            "This account is not allowed to use W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp due to spam",
            "Ask for review",
            "Chats are still on this device",
            "Are you sure you want to edit your number? You might need to verify it again.",
            "Register new number",
            "Register new number",
            "We've completed our review and found this account activity goes against our terms of service",
            "This account is not allowed to use W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp",
            "Submit",
            "Reviews typically take 24 hours. We'll notify you in W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp. Chats are still on this device.",
            "Request submitted",
            "Add notes to help our review (optional)",
            "Submitting…",
            "terms of service",
            "Our systems flagged your account accidentally. We apologize for this. Chats can be accessed after you verify your account.",
            "Chats can be accessed after you verify your account. You can learn more about using W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp responsibly in our Help Center.",
            "This account has been restored",
            "Review status",
            "Help Center",
            "We've completed your review. Select for more.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Support",
            "This may be a business. W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp hasn't verified their name yet.",
            "This business worked with other companies to manage this message.",
            "This message was secured with end-to-end encryption.",
            "This business used a secure service from Meta to manage this message.",
            "Couldn't block. Check your Internet connection and try again.",
            "You blocked this contact. Select to unblock.",
            "Blocked contacts will no longer be able to call you or send you messages.",
            "Select to learn more.",
            "This chat is with a business account.",
            "Business account",
            "Business Description",
            "Business Details",
            "Business Details",
            "By appointment only",
            "Closed",
            "Closed now",
            "Closed today",
            "Open 24 hours",
            "Open by appointment only",
            "Business Hours (local time)",
            "No Details found",
            "Accept",
            "On another call",
            "Calling",
            "Clear all call history",
            "Clearing all call history",
            "Connecting…",
            "Remove from call history",
            "Removing from call history",
            "End",
            "Call ended",
            "Call not answered",
            "Call declined",
            "Incoming call",
            "To make a call, press the call key in one of your chats.",
            "Incoming call",
            "Missed call",
            "Call info",
            "Message",
            "Outgoing call",
            "Call canceled",
            "Call declined",
            "Not answered",
            "Unavailable",
            "Missed call",
            "Mute",
            "Muted",
            "Call on hold",
            "Decline",
            "Ringing",
            "Speaker off",
            "Speaker on",
            "Start call?",
            "Unmute",
            "Call",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Call",
            "Caption",
            "Category",
            "Couldn't change admins. Please try again.",
            "You can't change admins because this group has ended.",
            "You can't change admins because you're not an admin.",
            "You can't change admins because you're not a participant.",
            "Updating group admins…",
            "Contacts help",
            "If some of your friends don't appear in the list:",
            "Make sure that your friend's phone number is in your address book",
            "Make sure that your friend is using W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp",
            "No W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp contacts",
            "Archive",
            "Mark as read",
            "Mark as unread",
            "Unarchive",
            "View business info",
            "View contact",
            "Group info",
            "Not found",
            "Delete",
            "Chats",
            "Choose a country",
            "Waiting for this message. This may take a while.",
            "Learn more.",
            "Clear chat",
            "Delete media from device",
            "Delete starred messages",
            "Clearing chat",
            "Your phone's date/time is inaccurate! Adjust your clock and try again.",
            "An error occured while linking device. Please try again",
            "Linked Devices",
            "Linking Device",
            "No linked devices",
            "Already blocked",
            "Hey there! I am using W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            "About and phone number",
            "Encryption",
            "Messages and calls are end-to-end encrypted. Select to verify.",
            "Messages are end-to-end encrypted. Select to verify.",
            "Profile photo removed",
            "Mobile",
            "Mute notifications",
            "Other actions",
            "Security",
            "This business works with other companies to manage this chat. Select to learn more.",
            "This business uses a secure service from Meta to manage this chat. Select to learn more.",
            "Starred messages",
            "Your email id",
            "Enter your email",
            "Describe your problem",
            "Enter your email address",
            "Enter a valid email address",
            "Invalid email",
            "Please provide more information or ask a question",
            "Invalid email",
            "Problem or question",
            "Contact us",
            "You",
            "Contacting W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp…",
            "Contacts",
            "Add to contacts",
            "Emoji",
            "Send picture",
            "Send video",
            "Forwarded",
            "Forwarded many times",
            "Group",
            "Jump to bottom",
            "Suspicious link",
            "Message",
            "Dismiss",
            "Copy",
            "Delete",
            "Forward",
            "Message info",
            "Keep",
            "Paste",
            "Star",
            "Unkeep",
            "Unstar",
            "Delete unsent voice message?",
            "Press ▲ or ▼ for volume",
            "Release to stop recording",
            "This business account is not in your contact list",
            "You were added by someone who’s not in your contacts",
            "The sender is not in your contact list",
            "This official business account is not in your contacts",
            "privacy settings",
            "VOICE",
            "Press again to record",
            "We cannot access phone storage data at the moment",
            "Reset the app. This will delete all your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp chats and media.",
            "Restart your phone and try again",
            "This business can’t chat with phone numbers with your country code.",
            "This business can’t chat with phone numbers with your country code.",
            "Using mobile data",
            "When roaming",
            "Connected on Wi-Fi",
            "Media auto-download",
            "Data usage",
            "It is impossible to reverse this action! If you reactivate your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp account in the future, your data will not be recovered.",
            "Delete your account?",
            "Deleting your account will delete your account info and profile photo, remove you from all W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp groups and delete your message history. Enter your country code and phone number to continue.",
            "Phone number",
            "The specified number doesn't match yours",
            "If you exit now your account may not be deleted.",
            "Deleting your account",
            "Delete my account",
            "Deleting chat",
            "Delete group",
            "You can't delete this group since you are a participant of it.",
            "Deleting group",
            "Delete for everyone",
            "Delete for me",
            "Your account was successfully deleted.",
            "Account deleted",
            "Your phone number is no longer registered on this phone. This is likely because you registered your phone number with W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp on a different phone.",
            "Something went wrong.",
            "Error",
            "Success",
            "Disappearing messages",
            "Make messages in this chat disappear",
            "For more privacy and storage, all new messages will disappear from this chat for everyone after the selected duration",
            "Default Message Timer",
            "Start new chats with disappearing messages set to your timer",
            "Start new chats with disappearing messages",
            "When enabled, all new individual chats will start with disappearing messages set to the selected duration. This setting will not affect your existing chats.",
            "Default Message Timer",
            "Update your default message timer in Settings",
            "Document",
            "Documents",
            "The emojis you use will appear here",
            "No results found",
            "Something went wrong.  Enter your number and try again.",
            "Something is wrong with your version of W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp. Please get the latest version from the Store.",
            "Something is wrong with your version of W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp. Please get the latest version from the JioStore.",
            "Something went wrong. You’ll need to verify your account again.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp will send an SMS message to verify your phone number. Carrier SMS charges may apply.",
            "Verify your phone number",
            "Send SMS",
            "You need to select a country",
            "Phone number",
            "Unable to connect. Check your Internet connection and try again.",
            "Unable to request SMS. Try call verification.",
            "Unable to send SMS. Please wait a few minutes before trying again.",
            "SMS to the number you provided failed. Check your number and try again.",
            "You tried SMS verification too many times. Try call verification.",
            "You have entered the wrong code too many times. Please contact customer support for assistance.",
            "You have requested your code too many times. Check with your mobile provider that you can receive SMS and phone calls and try again.",
            "You have entered the wrong code too many times. Please contact customer support for assistance.",
            "You have entered the wrong code too many times. Please check with your mobile provider that you can receive SMS and phone calls. Please wait for a new code to be sent and try again.",
            "You recently connected. Please try again later.",
            "Something went wrong. Please try again.",
            "Unable to request a call. Try SMS verification.",
            "Unable to call. Please wait a few minutes before trying again.",
            "Call to the number you provided failed. Check your number and try again later.",
            "You tried voice verification too many times. Try SMS verification.",
            ",",
            "Off",
            "This message disappeared and can't be forwarded.",
            "This message was sent while disappearing messages were turned off.",
            "Group admins control who can change this setting.",
            "Anyone in this chat can change this setting.",
            "Turning on this setting will make new messages disappear after the selected amount of time. Recipients can still save these messages elsewhere.",
            "You can't change this setting because you're not connected to the Internet. Check your Internet and try again.",
            "Disappearing Messages",
            "You can't turn off disappearing messages for this chat unless you unblock this contact.",
            "You can't turn on disappearing messages for this chat unless you unblock this contact.",
            "Disappearing Messages",
            "While this setting is on, new messages will disappear from this chat after a selected amount of time.",
            "Disappearing Messages Were Turned On",
            "Media and messages won’t disappear from outside the chat or from any devices they’re saved on.",
            "There are still ways for recipients to save messages, like forwarding them or taking a screenshot.",
            "Messages will disappear after a selected amount of time if they’re sent to a chat that has disappearing messages turned on.",
            "Get Started With Disappearing Messages",
            "Disappearing messages were turned off.",
            "This message has disappeared",
            "You turned off disappearing messages.",
            "This message will be marked as forwarded many times.",
            "Do you want to close the app?",
            "Exit group",
            "You can't exit this group since you aren't a participant of it anymore.",
            "Failed to leave. Check your Internet connection and try again.",
            "Your version of W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp is too old and is no longer supported. Please try again later or update W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp from the Store.",
            "No chats found",
            "No results found",
            "Recent chats",
            "Forward to…",
            "From Facebook",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Calling isn't supported on this phone.",
            "Document will appear here soon",
            "Live location messages aren't supported on this phone.",
            "This type of message isn't supported on this phone.",
            "Payments aren't supported on this phone.",
            "Stickers aren't supported on this phone.",
            "To use W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp, you must be at least 16 years old.",
            "Delete report",
            "Downloading…",
            "Export report",
            "Your report contains W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp account information. Only share it with people or apps you trust.",
            "Export report",
            "Request report",
            "Download report",
            "Request sent",
            "Delete report from your phone? Deleting the report will not delete any data from your account.",
            "Delete report",
            "Couldn't delete report. Request a new one.",
            "Couldn't download report. Try again.",
            "Couldn't request report. Try again.",
            "Couldn't download because your report expired. Request a new one.",
            "Couldn't save your report.",
            "Report Saved",
            "Your request will be canceled if you make changes to your account such as changing your number or deleting your account.",
            "Create a report of your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp account information and settings, which you can access or port to another app. This report does not include your messages.",
            "Your account info report is now available",
            "Learn more about how W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Ireland works with the Facebook companies.",
            "Restart",
            "Something went wrong. Please restart W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            "Allow W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp to use geolocation via “W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp” > “Geolocation” > “Grant”",
            "App permission",
            "Turn on geolocation in the setting screen",
            "Geolocation setting",
            "The GIFs you star will appear here",
            "Couldn't load GIFs.",
            "Check your Internet connection and try again.",
            "This GIF is not available.",
            "GIF",
            "Search GIFs",
            "You allowed all participants to send messages to this group",
            "You allowed only admins to send messages to this group",
            "Only admins can send messages",
            "You're no longer a participant",
            "You created this group",
            "Group creator created this group",
            "A participant changed the group description. Select to View.",
            "You changed the group description. Select to View.",
            "You deleted the group description",
            "Couldn't change the group description because another participant in this group changed the description recently.",
            "Couldn't change the group description because you're not an admin.",
            "Group description is too long.",
            "This group has ended",
            "Invite via link became unavailable. Select to learn more.",
            "Invite via link is temporarily unavailable for this group.",
            "Invite via link was temporarily unavailable for this group.",
            "You can’t view this group’s invite link because you’re not an admin.",
            "Invite via link became available again. Select to view the new link.",
            "Add group description",
            "Admin",
            "All participants",
            "You can't change this group's icon",
            "Setting send messages access",
            "Group description",
            "Enter new description",
            "Change description",
            "Group subject",
            "Enter new subject",
            "Change subject",
            "Choose photo",
            "Dismiss as admin",
            "Edit group info",
            "Choose who can change this group's subject, icon, description and disappearing messages setting.",
            "Messages and calls are end-to-end encrypted. Select for more info.",
            "Messages are end-to-end encrypted. Select for more info.",
            "Group icon removed",
            "You're no longer a participant",
            "Check your Internet connection and try again.",
            "Only admins",
            "Make group admin",
            "Remove",
            "Removing group description",
            "Remove group icon",
            "Save to Gallery",
            "There was a problem saving the photo",
            "Unable to save photo",
            "Photo successfully saved to Gallery",
            "Saving photo…",
            "Send messages",
            "Group Settings",
            "Group description",
            "You're already in this group",
            "The group invite link you tried to open is not correct",
            "Couldn't retrieve invite code. Please try again.",
            "Invite via link is temporarily unavailable for this group.",
            "Created by you",
            "Group invite",
            "Couldn't retrieve the group invite information. Please try again.",
            "Anyone with W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp can follow this link to join this group. Only share it with people you trust.",
            "You can't join this group because this invite link is invalid.",
            "Joining group",
            "Invite via link",
            "You can't join this group because this invite link was reset",
            "No contacts",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Group invite",
            "You can't join this group because you were removed",
            "You reset this group's invite link.",
            "Invite Link",
            "You can't join this group because it has ended",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp group",
            "You changed this group's settings to allow only admins to edit this group's info",
            "You were added",
            "You're no longer an admin",
            "You joined via an invite link",
            "You left",
            "You're now an admin",
            "You were removed",
            "You changed this group's icon",
            "You deleted this group's icon",
            "Something went wrong. Try using a different icon.",
            "Couldn't set the group icon. Please try again.",
            "Joining group",
            "You allowed all participants to change this group's info",
            "You allowed only admins to change this group's info",
            "Couldn't change this setting. Please try again.",
            "You can't change this setting because you're not a participant.",
            "You can't change settings because you're not an admin.",
            "Couldn't change the group subject. Please try again.",
            "Couldn't change the group subject because group does not exist.",
            "Couldn't change the group subject because you're not an admin.",
            "Couldn't change the group subject because you're no longer a participant.",
            "Group subject is too long.",
            "You changed this group's settings to allow all participants to edit this group's info",
            "Contact us",
            "Help Center",
            "Licenses",
            "Sending logs",
            "Terms and Privacy Policy",
            "Help",
            "Error",
            "Scan code",
            "Messages and calls are end to end encrypted",
            "Success",
            "Verify security code",
            "Retrieving security code. This may take a few seconds.",
            "This chat has been closed",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Support",
            "This chat has been closed",
            "This chat has been closed",
            "This chat is with the official account of W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Support.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp secures your messages and calls with this account.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp secures your messages with this account.",
            "Select to learn how messages and calls are secured.",
            "Select to learn how messages are secured.",
            "Exit",
            "Initializing…",
            "Enter 6-digit code",
            "Invalid country code",
            "The website address is not valid",
            "Send invite",
            "Delete invite",
            "Deleting invite",
            "Revoke invite",
            "Invite expired",
            "No invites found",
            "Group invite",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp group invite",
            "Invite to group",
            "Let's chat on W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp! It's a fast, simple and secure app we can use to message and call each other for free. Get it at https://whatsapp.com/dl",
            "Invite to W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp",
            "Couldn't join group. Please try again.",
            "You can't join this group because the invite link is unavailable.",
            "You can't join this group because it has ended.",
            "You can't join this group because you were removed.",
            "You can't join this group because this invite link was revoked.",
            "You can't join this group because it is full.",
            "Security code notifications are no longer available for this chat.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp encountered a problem and will close.",
            "Licenses",
            "Something went wrong. Please try again.",
            "Failed to load nearby places. Please try again.",
            "Please enable geolocation",
            "Location",
            "Change the setting(s) below to enable location sending",
            "Failed to retrieve location. Please try again.",
            "Could not retrieve location. Please enable geolocation.",
            "Show in chat",
            "Add emoji",
            "All changes will be discarded. Save changes?",
            "Save changes?",
            "Crop",
            "Discard",
            "Edit emoji",
            "Edit image",
            "None",
            "Rotate",
            "Apply",
            "No media",
            "This media is no longer available. Try downloading it again.",
            "Check your Internet connection and try again.",
            "Could not find this file on your phone.",
            "Media",
            "Off",
            "On",
            "Admins",
            "No admins found",
            "Message admin",
            "more",
            "Message could not be found. It may have been deleted.",
            "Update error",
            "If you exit now, the update will start from the beginning when you re-enter the app.",
            "Updating, please wait…",
            "Messages to this group are secured with end-to-end encryption, which means W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp and third parties can't read them.",
            "Verify",
            "Delivered",
            "Played",
            "Read",
            "Sent",
            "Opened",
            "1 week",
            "8 hours",
            "Always",
            "No contacts",
            "No contacts found",
            "New chat",
            "No contacts",
            "No contacts found",
            "Add new contact",
            "Reload contacts",
            "New group",
            "Group subject",
            "Type group subject",
            "Add group icon",
            "Group was not created. Check your Internet connection and try again.",
            "There are no applications on your phone that can open this file.",
            "No chats using storage",
            "Couldn't open link because no email applications are installed on your phone.",
            "No media",
            "Couldn't open document because you don't have a PDF reader. Open JioStore to find a PDF reader.",
            "Couldn't open document because you don't have a PDF reader. Open KaiOS store to find a PDF reader.",
            "No starred messages",
            "None",
            "Not enough storage space available. Free up space and try again.",
            "Show notifications when receiving messages in group chats",
            "Show notifications when receiving messages in a chat",
            "Preview message text inside new message notifications",
            "This message was deleted",
            "Select to edit.",
            "Select to view the new invite link.",
            "Group notifications",
            "Message notifications",
            "Show preview",
            "Notifications",
            "Official business account",
            "One or more messages will be marked as forwarded many times.",
            "Message",
            "Can't send. Not an Admin.",
            "No longer a participant",
            "Only report",
            "This phone number is invalid",
            "No internet",
            "Jump to message",
            "Invalid chat link",
            "The phone number in the link is invalid",
            "No internet",
            "Starting chat",
            "Forward",
            "Options",
            "Other contacts",
            "Your phone does not have enough space for W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp to run",
            "Remove",
            "Remove all W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp photos, videos and audio",
            "Remove W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp photos, videos and audio older than one week",
            "No space left",
            "Please wait… Your phone may restart after this operation.",
            "Deleting media",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Calling is unavailable in your country.",
            "Check your Internet connection and try again.",
            "Call could not connect",
            "Delete",
            "Check your Internet connection and try again.",
            "Retry creating group",
            "Creating group…",
            "Use this phone number for W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp?",
            "This phone number was requested and received from your mobile network",
            "Requesting your phone number…",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp will send an SMS message to verify your phone number. Carrier SMS charges may apply.",
            "Photo",
            "Photos",
            "No places found",
            "Turn the volume up",
            "You received a poll. Update your version of W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp to see polls.",
            "Business Account",
            "Online",
            "recording audio…",
            "typing…",
            "Privacy",
            "You changed your Name and About.",
            "You changed your About.",
            "You changed your Name.",
            "Save changes?",
            "About",
            "My name",
            "My phone number",
            "My profile photo",
            "My profile",
            "Name can't be empty.",
            "Name is too long.",
            "Add your profile photo so that your contacts can recognize you",
            "Who can see my photo",
            "There was an error trying to set up your profile picture.",
            "Something went wrong while setting your profile picture. Please try again.",
            "Later",
            "My profile",
            "All",
            "No reactions",
            "You received a reaction. Update your version of W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp to see reactions.",
            "99+ participants reacted",
            "Reacted to 99+ messages",
            "Reacted to 99+ messages",
            "Select to remove",
            "Show notifications for reactions to messages you send",
            "Reaction Notifications",
            "Reactions",
            "Remove from group",
            "Couldn't remove participant. Please try again.",
            "You can't remove participants because this group has ended.",
            "You can't remove participants because you're not an admin.",
            "You can't remove participants because you're not a participant.",
            "Couldn't remove participant. Check your Internet connection and try again.",
            "Removing…",
            "Block contact",
            "If you report this contact, the chat's history will also be deleted.",
            "Report",
            "Report this contact to W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp? They will be blocked and this chat's history will also be deleted.",
            "This contact will not be notified.",
            "Couldn't report. Check your Internet connection and try again.",
            "If you report and block, this chat's history will also be deleted.",
            "Report this group to W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp? You will be removed from it and this groups's chat history will also be deleted.",
            "If you report group and leave, this chat's history will also be deleted.",
            "Report group",
            "This message will be forwarded to W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            "Report user",
            "Report and block",
            "Report and leave",
            "Something went wrong. Please try again.",
            "Remember, if someone is in immediate danger, contact your local emergency services now.",
            "Report sent",
            "Sending report…",
            "Your phone number is banned from using W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.\nPlease contact customer support for assistance.",
            "Call me",
            "Call me",
            "The code you entered is incorrect. Please try again.",
            "You have entered the wrong code too many times.\nPlease contact customer support for assistance.",
            "Incorrect code",
            "Select 'Resend SMS' or 'Call me' first.",
            "Select 'Resend SMS' first.",
            "Resend SMS",
            "Resend",
            "The code you entered was sent too long ago and is no longer valid. Request another SMS or call to get a new code.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp is temporarily unavailable. Please try again later.",
            "Something went wrong. Please contact customer support for assistance.",
            "Requesting an SMS…",
            "Requesting a call…",
            "Reset",
            "The previous invite link is now reset and a new invite link has been created.",
            "Couldn't reset invite code. Please try again.",
            "Reset link is temporarily unavailable for this group.",
            "Retrieving location…",
            "Review and delete items",
            "Couldn't revoke invite. Please try again.",
            "You can't revoke this group invite because this group has ended.",
            "You can't revoke this group invite because you're not an admin.",
            "You can't revoke this group invite because you're not a participant.",
            "This message was deleted",
            "You deleted this message",
            "Scan Code",
            "Search",
            "You are always in control of the conversation. You can stop chatting with this business or block them at any time.\nW\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp secures your messages and calls with this business.\nFor details about how this chat is secured, select Learn More.",
            "You are always in control of the conversation. You can stop chatting with this business or block them at any time.\nW\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp secures your messages with this business.\nFor details about how this chat is secured, select Learn More.",
            "You are always in control of the conversation. You can stop chatting with this business or block them at any time.\nW\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp secures your messages and calls with this business.\nFor details about how this chat is secured, select Learn More.",
            "You are always in control of the conversation. You can stop chatting with this business or block them at any time.\nW\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp secures your messages with this business.\nFor details about how this chat is secured, select Learn More.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp secures your conversations with end-to-end encryption. Your messages and calls stay between you and the people and businesses you choose. Not even W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp can read or listen to them.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp secures your conversations with end-to-end encryption. Your messages stay between you and the people and businesses you choose. Not even W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp can read or listen to them.",
            "This business works with other companies to manage this chat.",
            "This business uses a secure service from Meta to manage this chat.",
            "Select for more info.",
            "This business is now working with other companies to manage this chat.",
            "This business is now using a secure service from Meta to manage this chat.",
            "Messages to this chat and calls are secured with end-to-end encryption.",
            "Messages to this chat are secured with end-to-end encryption.",
            "Messages and calls are end-to-end encrypted. No one outside of this chat, not even W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp, can read or listen to them.",
            "Messages and calls are now end-to-end encrypted. No one outside of this chat, not even W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp, can read or listen to them.",
            "Messages are end-to-end encrypted. No one outside of this chat, not even W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp, can read or listen to them.",
            "Messages are now end-to-end encrypted. No one outside of this chat, not even W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp, can read or listen to them.",
            "The selected image is too small",
            "Send location",
            "Add a caption…",
            "Failed to rotate media.",
            "Send place",
            "Failed to send place. Please try again.",
            "Something went wrong while updating your about. Please try again.",
            "Account",
            "My contacts except…",
            "Block contact",
            "Blocked",
            "Add new…",
            "Blocked",
            "My contacts",
            "Delete my account",
            "Everyone",
            "Nobody",
            "“Nobody“ is no longer supported. Do you want to change your setting? You won't be able to switch back.",
            "None",
            "Check your Internet connection and try again.",
            "About",
            "Couldn't update privacy setting. Please try again.",
            "Check your Internet connection and try again.",
            "Groups",
            "Admins who can't add you to a group will have the option of sending you a private invite.",
            "Who can add me to groups?",
            "Last seen",
            "If you don't share your Last Seen, you won't be able to see other people's Last Seen",
            "Profile photo",
            "Check your Internet connection and try again.",
            "Who can see my photo",
            "Read receipts",
            "If you turn off read receipts, you won't be able to see read receipts from other people. Read receipts are always sent for group chats.",
            "Show security notifications",
            "Messages and calls in end-to-end encrypted chats stay between you and the people you choose. Not even W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp can read or listen to them. Learn which chats are end-to-end encrypted.",
            "Messages in end-to-end encrypted chats stay between you and the people you choose. Not even W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp can read or listen to them. Learn which chats are end-to-end encrypted.",
            "Get notified when your security code changes for a contact in an end-to-end encrypted chat.",
            "Request account info",
            "Request account info",
            "Settings",
            "Chats",
            "Wallpaper",
            "Apply this Wallpaper to current chat or all chats?",
            "Apply Wallpaper in all chats, or default Wallpapers only",
            "Updating Wallpaper",
            "Wallpaper",
            "Show media in Gallery",
            "Show newly downloaded media in your phone's media apps (such as Gallery or Video), so they can be browsed and deleted more easily.",
            "Linked Devices",
            "Data usage",
            "You made changes to your selection.",
            "Save changes?",
            "Help",
            "Location",
            "Notifications",
            "Storage usage",
            "Settings",
            "1x",
            "1.5x",
            "2x",
            "Add",
            "Add contact",
            "Agree",
            "All",
            "Back",
            "Block",
            "Call",
            "Cancel",
            "Change",
            "Clear",
            "None",
            "Close",
            "Contact us",
            "Continue",
            "Default only",
            "Delete",
            "Deselect",
            "Disable",
            "Done",
            "Don't save",
            "Edit",
            "Enable",
            "Enter",
            "Exit",
            "Forgot PIN",
            "Help",
            "Scanning…",
            "Info",
            "Invite",
            "Join group",
            "Keep",
            "Learn more",
            "Link",
            "Load",
            "Loading…",
            "Filter",
            "More",
            "Mute",
            "New call",
            "Next",
            "No",
            "Not now",
            "OK",
            "Open",
            "Pause",
            "Remove",
            "Places",
            "Play",
            "Privacy",
            "QR code",
            "Remove",
            "Remove link preview",
            "Remove reply",
            "Reply",
            "Reply privately",
            "Report",
            "Reset account",
            "Reset",
            "Retry",
            "Review",
            "Rewind",
            "Rotate",
            "Save",
            "Search",
            "Select",
            "All",
            "All",
            "Select country",
            "None",
            "Send",
            "Send email",
            "Sending…",
            "Skip",
            "Stand by…",
            "Stop",
            "Search in store",
            "Terms & Policy",
            "Current",
            "Unblock",
            "View",
            "View all",
            "Views",
            "Zoom",
            "Zoom in",
            "Zoom out",
            "Select contacts",
            "Retrieving contacts",
            "Share to…",
            "No internet",
            "Starting chat",
            "Send to…",
            "This GIF failed to load. Check your Internet connection and try again.",
            "Updating, please wait…",
            "Starred Messages",
            "Starred Messages",
            "Add new",
            "Color",
            "No status found",
            "Send this status update to your contacts?",
            "This status has been deleted.",
            "This status has expired.",
            "Hide status updates?",
            "Muted updates",
            "Recent updates",
            "Viewed updates",
            "Sending messages and status update…",
            "Sending status update…",
            "Muted updates",
            "My status",
            "My status",
            "Privacy Settings",
            "Sending reply…",
            "Delete this status update? It will also be deleted for everyone who received it.",
            "Delete this status update?",
            "Send text",
            "Type a status",
            "sending…",
            "Couldn't send",
            "Your status updates will disappear after 24 hours.",
            "No views yet.",
            "Hide",
            "My contacts except…",
            "Hide status from…",
            "My contacts",
            "Changes to your privacy settings won't affect status updates that you've sent already",
            "Status",
            "Only share with…",
            "Share status with…",
            "Just now",
            "No status updates available",
            "Couldn't send",
            "View muted updates",
            "Sticker",
            "Chats",
            "Checking…",
            "Other",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Media",
            "Storage usage",
            "Messages to this chat are now secured with end-to-end encryption, which means third parties can't read or listen to them.",
            "This link contains unusual characters. It may be trying to appear as another site.",
            "Suspicious link",
            "Couldn't reload contacts. Check your Internet connection and try again.",
            "Please wait while your contacts refresh.",
            "Reloading contacts",
            "Calls",
            "Chats",
            "Status",
            "You're temporarily banned from W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp because you sent too many messages to a broadcast list.",
            "You're temporarily banned from W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp because you may have violated our terms of service.",
            "You're temporarily banned from W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp because you sent the same message to too many people.",
            "You're temporarily banned from W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp because too many people blocked you.",
            "Connected",
            "Copied to clipboard",
            "No internet",
            "Today",
            "To chat with this business, review and accept WhatApp's updated terms and privacy policy",
            "This update provides more information about how you can securely chat with businesses. You can review and accept the W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp update to chat with this business. Or select Not Now to view this message.",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp’s terms and privacy policy update",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp recently updated its terms and privacy policy. This business uses a secure service from Meta to manage chats. To chat with this business, review and accept the W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp update.",
            "Chat with this business",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp recently updated its terms and privacy policy. To chat with this business, review and accept the W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp update.",
            "Disable two-step verification?",
            "Confirm your email address.",
            "Confirm your PIN.",
            "Two-step verification is enabled. You'll need to enter your PIN when registering your phone number with W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp again.",
            "For added security, enable two-step verification, which will require a PIN when registering your phone number with W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp again.",
            "To continue, two-step verification will be disabled. You'll need to enable it again from W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp settings.",
            "A message was sent to the email address associated with this number.",
            "Add an email address to your account which will be used to reset your PIN if you forget it and safeguard your account.",
            "Enter a 6-digit PIN which you'll be asked for when you register your phone number with W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            "If you added an email address while setting up two-step verification, you can reset your PIN via email. Alternatively, you can reset your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp account to continue without a PIN.",
            "Forgot PIN",
            "Two-step verification",
            "You tried entering a PIN too many times. Contact support for assistance.",
            "Forgot PIN?",
            "Incorrect PIN. Try again.",
            "Your PIN is different from your SMS registration code.",
            "You entered your SMS registration code. Enter your two-step verification PIN which you created when you set up two-step verification.",
            "Confirm you want to reset your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp account.",
            "If you reset your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp account, you can finish registering without your PIN, but you'll be removed from your groups, and your pending messages and account info will be deleted.",
            "If you reset your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp account, you can finish registering without your PIN, but your pending messages will be deleted.",
            "Reset account",
            "You requested an email recently. Wait before requesting another one. If you haven't received your email, check your spam folder.",
            "Resetting account…",
            "Sending email…",
            "Add email address",
            "Change email address",
            "Change PIN",
            "Email addresses don't match. Try again.",
            "PINs don't match. Try again.",
            "Skip",
            "If you don't add an email address and you forget your PIN, you won't be able to re-register your phone number with W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            "Two-step verification",
            "Couldn't open the Store. Please try again.",
            "Couldn't unblock. Check your Internet connection and try again.",
            "You unblocked this contact",
            "Contact is blocked",
            "Unblock to add",
            "Unblock contact to place a W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp call",
            "Unblock contact to send a message",
            "Unmute",
            "Unmute",
            "99+ Unread Messages",
            "Check for software updates in your phone's Settings.",
            "Something went wrong. Please try again.",
            "Unable to connect. Check your Internet connection and try again.",
            "Something went wrong. Content is temporarily unavailable. Please try again later.",
            "Business account",
            "Contacts",
            "Verifying…",
            "Video",
            "Videos",
            "View caption",
            "Photo set to view once",
            "Video set to view once",
            "Photo expired",
            "Video expired",
            "View once",
            "Photo",
            "Video",
            "Opened",
            "Read",
            "For more privacy, your photo or video will disappear from the chat after the recipient opens it once. Remember, people can always take screenshots.",
            "Send photos and videos that can only be viewed once",
            "For more privacy, this photo will disappear after you close it.",
            "This photo is set to view once",
            "Read our Privacy Policy. Select “Agree” to accept the Terms of Service and continue.",
            "Welcome to W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp",
            "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp",
            "Yesterday",
            "This video doesn't exist.",
            "Check your Internet connection and try again.",
          ],
          dynamics: [
            (e) => ["Couldn't add ", e, "."],
            (e) => [
              "Couldn't add ",
              e,
              " because this business can't be added to groups.",
            ],
            (e) => [
              "You couldn't add ",
              e,
              " because they left the group recently. Try again later.",
            ],
            (e) =>
              1 === e
                ? `You couldn't add ${e} participant because they left the group recently. Try again later.`
                : `You couldn't add ${e} participants because they left the group recently. Try again later.`,
            (e) => ["You can't add ", e, " because this group is full."],
            (e) =>
              1 === e
                ? "Couldn't add participant. You can invite them privately to join this group."
                : `Couldn't add ${e} participants. You can invite them privately to join this group.`,
            (e) => [
              "Couldn't add ",
              e,
              ". You can invite them privately to join this group.",
            ],
            (e) => `Add participants (${e})`,
            (e) => `Audio (${e})`,
            (e, t) => [e, ": ", t],
            (e) => [
              "Before you can request a review, we will need to send you a SMS to verify your account. SMS will be sent to ",
              e,
            ],
            (e) => [
              "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Support will review your account and device info for activity that goes against our ",
              e,
            ],
            (e) => [
              "To verify your account we will send you an SMS with a verification code. SMS will be sent to ",
              e,
            ],
            (e) => [e, " is registered as a business account."],
            (e) => [e, " is registered as an official business account."],
            (e) => [
              e,
              " is registered as an official business account. The business is saved as a different name in your contacts.",
            ],
            (e) => [
              "This chat is with the official business account of ",
              e,
              ".",
            ],
            (e) => [
              "This chat is with the official business account of ",
              e,
              ". The business is saved as a different name in your contacts.",
            ],
            (e) => [
              e,
              " is now registered as a business account, instead of an official business account.",
            ],
            (e) => [
              "This chat is with the official business account of ",
              e,
              ".",
            ],
            (e) => [e, " is no longer registered as a business account."],
            (e) => [e, " is now registered as an official business account."],
            (e) => [
              e,
              " is no longer registered as an official business account.",
            ],
            (e) => `Closed now, opens at ${e} (local time)`,
            (e) => `Open until ${e} (local time)`,
            (e, t, o) => `Open until ${o}, ${t} - ${e} (local time)`,
            (e) => [
              "This official business account changed its name to ",
              e,
              ".",
            ],
            (e) => [
              "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp has verified that this is the official business account of ",
              e,
              ". This account is saved with a different name in your contact list.",
            ],
            (e) => [
              "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp has verified that this is the official business account of ",
              e,
              ".",
            ],
            (e) => ["Call ended (", e, ")"],
            (e, t) => [e, " (", t, ")"],
            (e, t, o) => [e, ", ", t, " (", o, ")"],
            (e) => ["Muted ", e],
            (e) => [
              "You can't dismiss ",
              e,
              " as admin because they created this group.",
            ],
            (e) => ["Clear chat with “", e, "”?"],
            (e) => ["Clear “", e, "”?"],
            (e) =>
              1 === e ? `Group in common (${e})` : `Groups in common (${e})`,
            (e) => "On until " + e,
            (e) => (1 === e ? e + " message" : e + " messages"),
            (e) => ["Message ", e],
            (e) => ["You can limit who can add you to groups in your ", e, "."],
            (e) => ["Delete chat with “", e, "”?"],
            (e) =>
              1 === e
                ? e +
                  " item will be deleted from your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp media, but it may still be saved on your device."
                : e +
                  " items will be deleted from your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp media, but they may still be saved on your device.",
            (e) => (1 === e ? `Delete ${e} item?` : `Delete ${e} items?`),
            (e) => ["Couldn't delete invite for ", e, ". Please try again."],
            (e) => ["No invite found for ", e, "."],
            (e) => ["Delete “", e, "”?"],
            (e) => [
              "Your security code with ",
              e,
              " changed because there was a login on a new device of theirs",
            ],
            (e) => [
              "Your security code with ",
              e,
              " changed because there was a logout from one of their devices",
            ],
            (e) => [
              "Your security code could not be verified with ",
              e,
              ". Select to learn more.",
            ],
            (e) => [
              "Your security code with ",
              e,
              " changed because there was a login or logout from one or more of their devices.",
            ],
            (e) => [
              "You use a default timer for disappearing messages in new chats. All new messages will disappear from this chat ",
              e,
              " after they're sent. Select to update your own default timer.",
            ],
            (e, t) => [
              e,
              " uses a default timer for disappearing messages in new chats. All new messages will disappear from this chat ",
              t,
              " after they're sent. Select to set your own default timer.",
            ],
            (e) => `Can't download media of ${e}MB or larger on this device.`,
            (e) => [
              "SMS will be sent to this phone number: ",
              e,
              ". Is this correct, or would you like to edit the number?",
            ],
            (e) =>
              `Your phone number ${e} is banned from using W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp. Contact support for help`,
            (e) => [
              "The phone number you entered is too long for the country: ",
              e,
            ],
            (e) => [
              "The phone number you entered is too short for the country: ",
              e,
              ". Include your area code if you haven't",
            ],
            (e, t) => [t, " is not a valid mobile number for the country ", e],
            (e) => ["Please wait ", e, " before entering your code."],
            (e) => ["Unable to request SMS. Try call verification in ", e, "."],
            (e) => [
              "Unable to send SMS. Please wait ",
              e,
              " before trying again.",
            ],
            (e) => [
              "SMS to the number you provided failed. Check your number and try again in ",
              e,
              ".",
            ],
            (e) => [
              "You tried SMS verification too many times. Try again in ",
              e,
            ],
            (e) => [
              "You tried SMS verification too many times. Try call verification in ",
              e,
            ],
            (e) => [
              "You have requested your code too many times. Check with your mobile provider that you can receive SMS and phone calls. Try again after ",
              e,
              ".",
            ],
            (e) => [
              "You have entered the wrong code too many times. Please check with your mobile provider that you can receive SMS and phone calls. Please wait for a new code to be sent. Try again after ",
              e,
              ".",
            ],
            (e) => [
              "You recently connected.  Please wait ",
              e,
              " before trying again.",
            ],
            (e) => [
              "Unable to request a call. Try SMS verification in ",
              e,
              ".",
            ],
            (e) => ["Unable to call. Please wait ", e, " before trying again."],
            (e) => [
              "Call to the number you provided failed. Check your number and try again in ",
              e,
              ".",
            ],
            (e) => [
              "You tried voice verification too many times. Try SMS verification in ",
              e,
            ],
            (e) => [e, " turned off disappearing messages."],
            (e, t) => [
              t,
              " turned on disappearing messages. New messages will disappear from this chat after ",
              e,
              ".",
            ],
            (e) => ["This message will disappear from the chat after ", e, "."],
            (e) => [
              "Disappearing messages were turned on. New messages will disappear from this chat after ",
              e,
              ".",
            ],
            (e) => [
              e,
              " turned off disappearing messages but this chat hasn't been updated yet.",
            ],
            (e) => [
              e,
              " turned on disappearing messages but this chat hasn't been updated yet.",
            ],
            (e) => [
              "You turned on disappearing messages. New messages will disappear from this chat after ",
              e,
              ".",
            ],
            (e) =>
              1 === e
                ? `You can only share with up to ${e} chat`
                : `You can only share with up to ${e} chats`,
            (e) => `Forward (${e})`,
            (e) => "Ready by " + e,
            (e) => "Your report has been saved to " + e,
            (e) =>
              1 === e
                ? `Your report will be ready in about ${e} day. You'll have a few weeks to download your report after it's available.`
                : `Your report will be ready in about ${e} days. You'll have a few weeks to download your report after it's available.`,
            (e) => "Your report is available to download until " + e,
            (e) => [
              e,
              " allowed all participants to send messages to this group",
            ],
            (e) => [e, " allowed only admins to send messages to this group"],
            (e) => ["Creating “", e, "”"],
            (e) => [
              "Can't create group ”",
              e,
              "” because you've created too many groups too quickly. Try again later.",
            ],
            (e) => [
              "The subject ”",
              e,
              "” is too long. Please make it shorter.",
            ],
            (e) => [
              "Can't create group ”",
              e,
              "” because you've created too many groups. Try again later.",
            ],
            (e) => [
              "There was an error creating group ”",
              e,
              "”. Try again later.",
            ],
            (e) => ["Group creator created group “", e, "”"],
            (e, t) => [e, " created group “", t, "”"],
            (e) => [e, " created this group"],
            (e) => ["You created group “", e, "”"],
            (e) => [e, " changed the group description. Select to View."],
            (e) => [e, " deleted the group description"],
            (e) => [
              "You can't dismiss ",
              e,
              " as admin because they created this group.",
            ],
            (e) => ["Exit “", e, "”?"],
            (e) => (1 === e ? e + " Invite" : e + " Invites"),
            (e) => (1 === e ? e + " participant" : e + " participants"),
            (e, t) => ["Remove ", t, " from “", e, "” group?"],
            (e) => [
              "You can't remove ",
              e,
              " because they created this group.",
            ],
            (e) => ["Created by ", e],
            (e) => "+" + e,
            (e) => [
              "Follow this link to join my W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp group - ",
              e,
            ],
            (e) => [e, " reset this group's invite link."],
            (e) => e + " not in contacts",
            (e) => (1 === e ? e + " participant" : e + " participants"),
            (e) => [
              e,
              " changed this group's settings to allow only admins to edit this group's info",
            ],
            (e) => [e, " changed their phone number to a new number."],
            (e) => [e, " joined using your invite"],
            (e) => [e, " was added"],
            (e) => ["A participant added ", e],
            (e) => ["A participant added ", e],
            (e) => [e, " joined via an invite link"],
            (e) => [e, " left"],
            (e) => ["A participant removed ", e],
            (e) => ["A participant removed ", e],
            (e, t) => [e, " added ", t],
            (e, t) => [e, " added ", t],
            (e) => [e, " added you"],
            (e, t) => [e, " removed ", t],
            (e, t) => [e, " removed ", t],
            (e) => [e, " removed you"],
            (e) => ["You added ", e],
            (e) => ["You added ", e],
            (e) => ["You removed ", e],
            (e) => ["You removed ", e],
            (e) => [e, " changed this group's icon"],
            (e) => [e, " deleted this group's icon"],
            (e) => [e, " allowed all participants to change this group's info"],
            (e) => [e, " allowed only admins to change this group's info"],
            (e) => ["A participant changed the subject to “", e, "”"],
            (e, t) => [e, " changed the subject to “", t, "”"],
            (e) => ["You changed the subject to “", e, "”"],
            (e) => [
              e,
              " changed this group's settings to allow all participants to edit this group's info",
            ],
            (e) => "Version " + e,
            (e) => "You're about to open " + e,
            (e) => [
              "This happened likely because ",
              e,
              " or you recently changed which devices you use W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp on. Please verify the security code again.",
            ],
            (e) => ["Your security code with ", e, " changed"],
            (e) => [
              "To verify that messages and calls with ",
              e,
              " are end-to-end encrypted, scan this code on their phone. You can also compare the number above instead.",
            ],
            (e, t) =>
              1 === e
                ? [
                    "To verify that messages and calls with ",
                    t,
                    " are end-to-end encrypted, scan this code on their phone and ",
                    e,
                    " other linked device. You can also compare the number above instead.",
                  ]
                : [
                    "To verify that messages and calls with ",
                    t,
                    " are end-to-end encrypted, scan this code on their phone and ",
                    e,
                    " other linked devices. You can also compare the number above instead.",
                  ],
            (e) => ["To verify, send a message to ", e, " and try again."],
            (e) => [
              "You opened verification for the wrong phone number. Open it for the correct phone number to verify ",
              e,
              ".",
            ],
            (e) => [
              "The phone number you entered is invalid for the country: ",
              e,
              ".",
            ],
            (e) =>
              1 === e
                ? `Invite expires in ${e} day`
                : `Invite expires in ${e} days`,
            (e) => "Invite expires at " + e,
            (e) => [
              "Your security code with ",
              e,
              " changed because there was a registration on a new device of theirs",
            ],
            (e) => [
              "Your security code with ",
              e,
              " changed. Select to learn more.",
            ],
            (e) => `Larger than ${e} MB`,
            (e) => "Last seen " + e,
            (e, t) => `Last seen ${e} at ${t}`,
            (e) => "Last seen at " + e,
            (e, t) => `Last seen ${t} at ${e}`,
            (e) => "Last seen yesterday at " + e,
            (e) => `This device can't send media files larger than ${e}MB.`,
            (e) => (1 === e ? `Forwarded ${e} time` : `Forwarded ${e} times`),
            (e) => e + " remaining",
            (e) => `New chat (${e})`,
            (e) => (1 === e ? `Participant (${e})` : `Participants (${e})`),
            (e) => `New group (${e})`,
            (e) => `New group (${e})`,
            (e) => [
              "Couldn't open chat with ",
              e,
              ". Check your phone's internet connection and try again.",
            ],
            (e) => [
              e,
              " is not on W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            ],
            (e) => [
              "Couldn't open chat with ",
              e,
              ". Check your phone's internet connection and try again.",
            ],
            (e) => [
              e,
              " is not on W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            ],
            (e) => [
              e,
              " is in a country where W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp Calling is unavailable.",
            ],
            (e) => [
              e,
              " is unable to receive W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp calls at this time.",
            ],
            (e) => [
              e,
              " is unable to receive W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp calls.",
            ],
            (e) => [
              e,
              " is unable to receive W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp calls at this time.",
            ],
            (e) => [
              e,
              " is not registered on W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            ],
            (e) => (1 === e ? e + " page" : e + " pages"),
            (e) => ["Cancel creation of group “", e, "”?"],
            (e) => [e, " is recording audio…"],
            (e) => [e, " is typing…"],
            (e) => `“${e}”`,
            (e) => e + "+",
            (e) => [e, " and 99+ others reacted"],
            (e, t) =>
              1 === t
                ? [e, " and ", t, " other reacted"]
                : [e, " and ", t, " others reacted"],
            (e) =>
              1 === e
                ? e + " participant reacted"
                : e + " participants reacted",
            (e, t) => ["Reacted ", t, " to “", e, "”"],
            (e) =>
              1 === e ? `Reacted to ${e} message` : `Reacted to ${e} messages`,
            (e, t) => [e, " @ ", t],
            (e) =>
              1 === e ? `Reacted to ${e} message` : `Reacted to ${e} messages`,
            (e, t) => ["Reacted ", t, " to “", e, "”"],
            (e) => ["Can't remove ", e, ". Please try again."],
            (e) => ["Can't remove ", e, " because they created this group."],
            (e) => ["Report ", e],
            (e) => [
              "The code you entered is incorrect. Please try again in ",
              e,
              ".",
            ],
            (e) => [
              "W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp is temporarily unavailable. Please try again in ",
              e,
              ".",
            ],
            (e) => ["Retry again in ", e, "."],
            (e) => ["Verify ", e],
            (e) => ["Waiting to automatically detect an SMS sent to ", e],
            (e) => [
              "Are you sure you want to reset the invite link for '",
              e,
              "'? If you reset the link, no one will be able to use it to join this group.",
            ],
            (e) => [
              "Messages to this chat are now secured with end-to-end encryption, which means W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp and third parties can't read or listen to them. ",
              e,
              " may use a service to store, read and respond to your messages. Contact ",
              e,
              " for information on their privacy practices.",
            ],
            (e) => [
              "Messages to this chat are now secured with end-to-end encryption. ",
              e,
              " may use another company to store, read and respond to your messages and calls.",
            ],
            (e) => [
              "Messages to this chat are now secured with end-to-end encryption. ",
              e,
              " may use another company to store, read and respond to your messages.",
            ],
            (e) =>
              1 === e ? e + " contact excluded" : e + " contacts excluded",
            (e) => (1 === e ? e + " contact" : e + " contacts"),
            (e) =>
              1 === e
                ? `You can only send up to ${e} contact`
                : `You can only send up to ${e} contacts`,
            (e) => `Select contacts (${e})`,
            (e) => `Share (${e})`,
            (e) => [e, " is not a phone number"],
            (e) => [
              "Couldn't open chat with ",
              e,
              ". Check your phone's internet connection and try again.",
            ],
            (e) => [
              e,
              " is not on W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp.",
            ],
            (e) => `Send (${e})`,
            (e, t) => `${e} of ${t}`,
            (e) =>
              1 === e
                ? `Send this status update to ${e} contact?`
                : `Send this status update to ${e} contacts?`,
            (e) => [
              e,
              " won't see your future status updates. You can change this in Privacy Settings.",
            ],
            (e) => [
              "New status updates from ",
              e,
              " won't appear under recent updates anymore.",
            ],
            (e) => ["Mute ", e, "?"],
            (e) => e + " new",
            (e) => [
              "Can't see views because you disabled Read Receipts in ",
              e,
              ".",
            ],
            (e) =>
              1 === e
                ? `Your status update cannot exceed ${e} character.`
                : `Your status update cannot exceed ${e} characters.`,
            (e) => "Sending " + e,
            (e) => "Couldn't send " + e,
            (e) => (1 === e ? e + " view" : e + " views"),
            (e) =>
              1 === e ? e + " contact excluded" : e + " contacts excluded",
            (e) =>
              1 === e ? e + " contact selected" : e + " contacts selected",
            (e) => (1 === e ? `Up to ${e} character` : `Up to ${e} characters`),
            (e) => (1 === e ? e + " minute ago" : e + " minutes ago"),
            (e) => "Today, " + e,
            (e) => "Yesterday, " + e,
            (e) => [
              "New status updates from ",
              e,
              " will appear under recent updates.",
            ],
            (e) => ["Unmute ", e, "?"],
            (e) => (1 === e ? e + " update" : e + " updates"),
            (e) =>
              1 === e
                ? `Your video was not sent because it's over ${e} second long`
                : `Your video was not sent because it's over ${e} seconds long`,
            (e) => (1 === e ? `Up to ${e} second` : `Up to ${e} seconds`),
            (e) => [e, " free"],
            (e) => [e, " used"],
            (e) => ["This is the official business account of ", e, "."],
            (e) => [
              "You're temporarily banned from W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp because you created too many groups with people who don’t have ",
              e,
              " in their address books.",
            ],
            (e) => [
              "You're temporarily banned from W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp because you sent too many messages to people who don’t have ",
              e,
              " in their address books.",
            ],
            (e) => [
              e,
              " You'll be able to use W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp again in:",
            ],
            (e) => (1 === e ? e + " day" : e + " days"),
            (e) => (1 === e ? e + " hour" : e + " hours"),
            (e) => (1 === e ? e + " minute" : e + " minutes"),
            (e) => (1 === e ? e + " second" : e + " seconds"),
            (e) => "Today, " + e,
            (e) => `Can't share more than ${e} media items.`,
            (e) => [
              "If you added an email address while setting up two-step verification, you can reset your PIN via email. Alternatively, in ",
              e,
              ", you can reset your W\ufeffh\ufeffa\ufefft\ufeffs\ufeffA\ufeffp\ufeffp account to continue without a PIN.",
            ],
            (e, t) => [
              "This account is protected by two-step verification. Enter the PIN you created when you set up two-step verification. ",
              t,
              " ",
              e,
            ],
            (e) => [
              "Enter the PIN you used when setting up two-step verification. You'll be asked for it periodically to help you remember it. ",
              e,
            ],
            (e) => ["Unblock ", e],
            (e) => e + " B",
            (e) => e + " GB",
            (e) => e + " KB",
            (e) => e + " MB",
            (e) => (1 === e ? e + " Unread Message" : e + " Unread Messages"),
            (e) =>
              1 === e
                ? "Can't send this contact because it's too large"
                : "Can't send these contacts because they're too large",
            (e, t) =>
              1 === e
                ? [t, " and ", e, " other contact"]
                : [t, " and ", e, " other contacts"],
            (e) => (1 === e ? e + " contact" : e + " contacts"),
            (e) => [
              "This view once photo has expired. Please ask ",
              e,
              " to re-send it.",
            ],
            (e) => [
              "This view once video has expired. Please ask ",
              e,
              " to re-send it.",
            ],
            (e) => `Voice message (${e})`,
            (e) => e + " more",
            (e) => "Yesterday, " + e,
          ],
          translateInt: function (e) {
            return e.toString();
          },
          zero: "0",
          countries: function () {
            return o
              .e(35)
              .then(o.t.bind(null, 541, 3))
              .then((e) => e.default);
          },
        });
    },
  },
]);
